<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ApduCommandsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('apdu_commands')->delete();
        
        \DB::table('apdu_commands')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'SelectBeCard',
                'apdu' => '00 A4 04 00 09 42 45 43 61 72 64 4F 74 70',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Applet selection',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'WriteConfigData',
                'apdu' => '00 D0 00 00 37',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 10000,
                'description' => 'Write the basic applet config data',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ReadNfcToken',
                'apdu' => '00 B0 02 00 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Return last generated HOTP',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'EraseNfcToken',
                'apdu' => '00 D0 03 00 00',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 1000,
                'description' => 'Erase last generated HOTP',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ReadVersionInfo',
                'apdu' => '00 B0 06 00 42',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Return applet version info',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'WriteVersionInfo',
                'apdu' => '00 D0 06 00 40',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 30000,
                'description' => 'Write applet version info',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'FactoryReset',
                'apdu' => '00 D0 08 00 10',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 30000,
                'description' => 'Reset card configuration',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ReadRsaPub_0',
                'apdu' => '00 B0 0A 00 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string_chunk',
                'timeout' => 0,
                'description' => 'Return the public key chunk 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ReadRsaPub_1',
                'apdu' => '00 B0 0A 01 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string_chunk',
                'timeout' => 0,
                'description' => 'Return the public key chunk 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'WriteEncryptedSequenceKey',
                'apdu' => '00 B0 08 00 0F',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 5000,
                'description' => 'write OTP secret key, RSA encrypted',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'WriteEncryptedResetCode',
                'apdu' => '00 D0 0E 00 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 30000,
                'description' => 'write card factory reset, RSA encrypted',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'ReadSequenceInfo_0',
                'apdu' => '00 B0 10 00 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'ReadSequenceInfo_1',
                'apdu' => '00 B0 10 01 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'ReadSequenceInfo_2',
                'apdu' => '00 B0 10 02 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'ReadSequenceInfo_3',
                'apdu' => '00 B0 10 03 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'ReadSequenceInfo_4',
                'apdu' => '00 B0 10 04 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'ReadSequenceInfo_5',
                'apdu' => '00 B0 10 05 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'ReadSequenceInfo_6',
                'apdu' => '00 B0 10 06 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 6',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ReadSequenceInfo_7',
                'apdu' => '00 B0 10 07 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 7',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ReadSequenceInfo_8',
                'apdu' => '00 B0 10 08 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 8',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'ReadSequenceInfo_9',
                'apdu' => '00 B0 10 09 10',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 0,
                'description' => 'Get rules for the request sequence number 9',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'ReadOtpToken_0',
                'apdu' => '00 B0 26 00 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ReadOtpToken_1',
                'apdu' => '00 B0 26 01 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ReadOtpToken_2',
                'apdu' => '00 B0 26 02 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ReadOtpToken_3',
                'apdu' => '00 B0 26 03 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ReadOtpToken_4',
                'apdu' => '00 B0 26 04 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ReadOtpToken_5',
                'apdu' => '00 B0 26 05 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ReadOtpToken_6',
                'apdu' => '00 B0 26 06 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 6',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ReadOtpToken_7',
                'apdu' => '00 B0 26 07 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 7',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ReadOtpToken_8',
                'apdu' => '00 B0 26 08 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 8',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'ReadOtpToken_9',
                'apdu' => '00 B0 26 09 2D',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get OTP for the request sequence number 9',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'ReadOtpPayloadToken_0',
                'apdu' => '00 B0 12 00 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 0  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'ReadOtpPayloadToken_1',
                'apdu' => '00 B0 12 01 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 1  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'ReadOtpPayloadToken_2',
                'apdu' => '00 B0 12 02 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 2  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'ReadOtpPayloadToken_3',
                'apdu' => '00 B0 12 03 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 3  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ReadOtpPayloadToken_4',
                'apdu' => '00 B0 12 04 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 4  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'ReadOtpPayloadToken_5',
                'apdu' => '00 B0 12 05 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 5  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'ReadOtpPayloadToken_6',
                'apdu' => '00 B0 12 06 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 6  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'ReadOtpPayloadToken_7',
                'apdu' => '00 B0 12 07 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 7  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'ReadOtpPayloadToken_8',
                'apdu' => '00 B0 12 08 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 8  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'ReadOtpPayloadToken_9',
                'apdu' => '00 B0 12 09 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => 'string',
                'timeout' => 0,
                'description' => 'Get HOTP for the request sequence number 9  using the given payload',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'WriteSequenceInfo_0',
                'apdu' => '00 D0 10 00 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 0 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'WriteSequenceInfo_1',
                'apdu' => '00 D0 10 01 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 1 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'WriteSequenceInfo_2',
                'apdu' => '00 D0 10 02 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 2 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'WriteSequenceInfo_3',
                'apdu' => '00 D0 10 03 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 3 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'WriteSequenceInfo_4',
                'apdu' => '00 D0 10 04 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 4 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'WriteSequenceInfo_5',
                'apdu' => '00 D0 10 05 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 5 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'WriteSequenceInfo_6',
                'apdu' => '00 D0 10 06 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 6 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'WriteSequenceInfo_7',
                'apdu' => '00 D0 10 07 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 7 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'WriteSequenceInfo_8',
                'apdu' => '00 D0 10 08 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 8 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'WriteSequenceInfo_9',
                'apdu' => '00 D0 10 09 63',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'configure 9 sequence',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'ReadUserInfo',
                'apdu' => '00 B0 14 00 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userInfo',
                'timeout' => 0,
                'description' => 'Get 80 bytes USER info',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'WriteUserInfo',
                'apdu' => '00 D0 14 00 50',
                'channel' => 'all',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write user info where in 0x00 config state',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'ReadConfigState',
                'apdu' => '00 B0 16 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'byte',
                'timeout' => 0,
                'description' => 'Get config status',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'WriteConfigState_0',
                'apdu' => '00 D0 16 03 00',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write config status 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'WriteConfigState_1',
                'apdu' => '00 D0 16 03 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write config status 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'WriteConfigState_2',
                'apdu' => '00 D0 16 03 02',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write config status 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'WriteConfigState_3',
                'apdu' => '00 D0 16 03 03',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write config status 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'WriteConfigState_4',
                'apdu' => '00 D0 16 03 04',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write config status 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'ReadCardState',
                'apdu' => '00 B0 18 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'byte',
                'timeout' => 0,
                'description' => 'Write config status 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'ReadCardOffImage_0',
                'apdu' => '00 B0 1A 00 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'ReadCardOffImage_1',
                'apdu' => '00 B0 1A 01 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'ReadCardOffImage_2',
                'apdu' => '00 B0 1A 02 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'ReadCardOffImage_3',
                'apdu' => '00 B0 1A 03 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'ReadCardOffImage_4',
                'apdu' => '00 B0 1A 04 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'ReadCardOffImage_5',
                'apdu' => '00 B0 1A 05 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'ReadCardOffImage_6',
                'apdu' => '00 B0 1A 06 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 6',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'ReadCardOffImage_7',
                'apdu' => '00 B0 1A 07 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 7',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'ReadCardOffImage_8',
                'apdu' => '00 B0 1A 08 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 8',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'ReadCardOffImage_9',
                'apdu' => '00 B0 1A 09 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 9',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'ReadCardOffImage_10',
                'apdu' => '00 B0 1A 0A 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 10',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'ReadCardOffImage_11',
                'apdu' => '00 B0 1A 0B 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 11',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'ReadCardOffImage_12',
                'apdu' => '00 B0 1A 0C 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 12',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'ReadCardOffImage_13',
                'apdu' => '00 B0 1A 0D 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 13',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'ReadCardOffImage_14',
                'apdu' => '00 B0 1A 0E 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 14',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'ReadCardOffImage_15',
                'apdu' => '00 B0 1A 0F 50',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'image',
                'timeout' => 0,
                'description' => 'Get the card off image block 15',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'WriteCardOffImage_0',
                'apdu' => '00 D0 1A 00 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'WriteCardOffImage_1',
                'apdu' => '00 D0 1A 01 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'WriteCardOffImage_2',
                'apdu' => '00 D0 1A 02 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'WriteCardOffImage_3',
                'apdu' => '00 D0 1A 03 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'WriteCardOffImage_4',
                'apdu' => '00 D0 1A 04 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'WriteCardOffImage_5',
                'apdu' => '00 D0 1A 05 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'WriteCardOffImage_6',
                'apdu' => '00 D0 1A 06 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 6',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'WriteCardOffImage_7',
                'apdu' => '00 D0 1A 07 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 7',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'WriteCardOffImage_8',
                'apdu' => '00 D0 1A 08 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 8',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'WriteCardOffImage_9',
                'apdu' => '00 D0 1A 09 FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 9',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'WriteCardOffImage_10',
                'apdu' => '00 D0 1A 0A FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 10',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'WriteCardOffImage_11',
                'apdu' => '00 D0 1A 0B FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 11',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'WriteCardOffImage_12',
                'apdu' => '00 D0 1A 0C FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 12',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'WriteCardOffImage_13',
                'apdu' => '00 D0 1A 0D FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 13',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'WriteCardOffImage_14',
                'apdu' => '00 D0 1A 0E FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 14',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'WriteCardOffImage_15',
                'apdu' => '00 D0 1A 0F FF',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 3000,
                'description' => 'Write  the card off image block 15',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'WriteFpsTimeout_0',
                'apdu' => '00 D0 24 00 03 01 00 00',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the FPS timeout 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'WriteFpsTimeout_1',
                'apdu' => '00 D0 24 00 03 01 00 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the FPS timeout 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'WriteFpsTimeout_2',
                'apdu' => '00 D0 24 00 03 01 00 02',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the FPS timeout 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'WriteFpsTimeout_3',
                'apdu' => '00 D0 24 00 03 01 00 03',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the FPS timeout 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'ExecuteActivateBtl',
                'apdu' => '00 D0 24 00 03 02 00 02',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Activate bluetooth mode',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'ExecuteActivateOnline',
                'apdu' => '00 D0 24 00 03 02 00 01',
                'channel' => 'BTL',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Activate online mode',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'ExecutePowerOff',
                'apdu' => '00 D0 24 00 03 03 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Power off the card',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'ExecuteAddInfo',
                'apdu' => '00 D0 24 00 03 04 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Adds sequence counter, battery level to card display',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'ExecuteLedIntensity_0',
                'apdu' => '00 D0 24 00 03 05 00 00',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the led intensity to 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'ExecuteLedIntensity_1',
                'apdu' => '00 D0 24 00 03 05 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Set the led intensity to 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'ExecuteSelfTest',
                'apdu' => '00 D0 24 00 03 06 00 01',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Execute internal self test',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'ExecuteBootLoader',
                'apdu' => '00 D0 24 00 03 07 00 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 500,
                'description' => 'Put the card in bluetooth mode recognized as CARDLAB OTA',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'ExecuteMcuReset',
                'apdu' => '00 D0 24 00 03 08 00 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Reset MCU',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'ExecuteActivateCharge',
                'apdu' => '00 D0 24 00 03 09 00 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 300,
                'description' => 'Power off the card and activare nfc charging mode',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'ExecuteSnap',
                'apdu' => '00 D0 24 00 03 0A 00 01',
                'channel' => 'NFC',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 300,
                'description' => 'Snap the card',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'ReadBatteryLevel',
                'apdu' => '00 B0 28 00 04',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'small_int',
                'timeout' => 300,
                'description' => 'Get battery status informations',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Read4kUserData_0',
                'apdu' => '00 B0 2A 00 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'Read4kUserData_1',
                'apdu' => '00 B0 2A 01 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Read4kUserData_2',
                'apdu' => '00 B0 2A 02 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 2',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Read4kUserData_3',
                'apdu' => '00 B0 2A 03 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 3',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Read4kUserData_4',
                'apdu' => '00 B0 2A 04 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 4',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Read4kUserData_5',
                'apdu' => '00 B0 2A 05 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 5',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Read4kUserData_6',
                'apdu' => '00 B0 2A 06 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 6',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Read4kUserData_7',
                'apdu' => '00 B0 2A 07 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 7',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Read4kUserData_8',
                'apdu' => '00 B0 2A 08 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 8',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Read4kUserData_9',
                'apdu' => '00 B0 2A 09 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 9',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Read4kUserData_10',
                'apdu' => '00 B0 2A 0A 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 10',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'Read4kUserData_11',
                'apdu' => '00 B0 2A 0B 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 11',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'Read4kUserData_12',
                'apdu' => '00 B0 2A 0C 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 12',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'Read4kUserData_13',
                'apdu' => '00 B0 2A 0D 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 13',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'Read4kUserData_14',
                'apdu' => '00 B0 2A 0E 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 14',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'Read4kUserData_15',
                'apdu' => '00 B0 2A 0F 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 15',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'Read4kUserData_16',
                'apdu' => '00 B0 2A 10 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 16',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'Read4kUserData_17',
                'apdu' => '00 B0 2A 11 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 17',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'Read4kUserData_18',
                'apdu' => '00 B0 2A 12 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 18',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'Read4kUserData_19',
                'apdu' => '00 B0 2A 13 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 19',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'Read4kUserData_20',
                'apdu' => '00 B0 2A 14 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 20',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'Read4kUserData_21',
                'apdu' => '00 B0 2A 15 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 21',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'Read4kUserData_22',
                'apdu' => '00 B0 2A 16 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 22',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'Read4kUserData_23',
                'apdu' => '00 B0 2A 17 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 23',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'Read4kUserData_24',
                'apdu' => '00 B0 2A 18 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 24',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'Read4kUserData_25',
                'apdu' => '00 B0 2A 19 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 25',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'Read4kUserData_26',
                'apdu' => '00 B0 2A 1A 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 26',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'Read4kUserData_27',
                'apdu' => '00 B0 2A 1B 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 27',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'Read4kUserData_28',
                'apdu' => '00 B0 2A 1C 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 28',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'Read4kUserData_29',
                'apdu' => '00 B0 2A 1D 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 29',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'Read4kUserData_30',
                'apdu' => '00 B0 2A 1E 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 30',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'Read4kUserData_31',
                'apdu' => '00 B0 2A 1F 80',
                'channel' => 'all',
                'requireData' => 0,
                'responseType' => 'userData',
                'timeout' => 500,
                'description' => 'Read 4k user data by chunk 31',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'Write4kUserData_0',
                'apdu' => '00 D0 2A 00 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 0',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'Write4kUserData_1',
                'apdu' => '00 D0 2A 01 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 1',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'Write4kUserData_2',
                'apdu' => '00 D0 2A 02 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 2',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'Write4kUserData_3',
                'apdu' => '00 D0 2A 03 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 3',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'Write4kUserData_4',
                'apdu' => '00 D0 2A 04 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 4',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'Write4kUserData_5',
                'apdu' => '00 D0 2A 05 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 5',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'Write4kUserData_6',
                'apdu' => '00 D0 2A 06 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 6',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'Write4kUserData_7',
                'apdu' => '00 D0 2A 07 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 7',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'Write4kUserData_8',
                'apdu' => '00 D0 2A 08 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 8',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'Write4kUserData_9',
                'apdu' => '00 D0 2A 09 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 9',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'Write4kUserData_10',
                'apdu' => '00 D0 2A 0A 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 10',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'Write4kUserData_11',
                'apdu' => '00 D0 2A 0B 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 11',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'Write4kUserData_12',
                'apdu' => '00 D0 2A 0C 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 12',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'Write4kUserData_13',
                'apdu' => '00 D0 2A 0D 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 13',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'Write4kUserData_14',
                'apdu' => '00 D0 2A 0E 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 14',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'Write4kUserData_15',
                'apdu' => '00 D0 2A 0F 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 15',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'Write4kUserData_16',
                'apdu' => '00 D0 2A 10 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 16',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'Write4kUserData_17',
                'apdu' => '00 D0 2A 11 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 17',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'Write4kUserData_18',
                'apdu' => '00 D0 2A 12 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 18',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'Write4kUserData_19',
                'apdu' => '00 D0 2A 13 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 19',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'Write4kUserData_20',
                'apdu' => '00 D0 2A 14 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 20',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'Write4kUserData_21',
                'apdu' => '00 D0 2A 15 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 21',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'Write4kUserData_22',
                'apdu' => '00 D0 2A 16 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 22',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'Write4kUserData_23',
                'apdu' => '00 D0 2A 17 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 23',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'Write4kUserData_24',
                'apdu' => '00 D0 2A 18 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 24',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'Write4kUserData_25',
                'apdu' => '00 D0 2A 19 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 25',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'Write4kUserData_26',
                'apdu' => '00 D0 2A 1A 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 26',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'Write4kUserData_27',
                'apdu' => '00 D0 2A 1B 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 27',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'Write4kUserData_28',
                'apdu' => '00 D0 2A 1C 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 28',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'Write4kUserData_29',
                'apdu' => '00 D0 2A 1D 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 29',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'Write4kUserData_30',
                'apdu' => '00 D0 2A 1E 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 30',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'Write4kUserData_31',
                'apdu' => '00 D0 2A 1F 80',
                'channel' => 'NFC',
                'requireData' => 1,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Write 4k user data by chunk 31',
                'crc' => 'Iso3309Crc16',
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'BtlEnroll0',
                'apdu' => '00 E0 00 00',
                'channel' => 'BTL',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 1000,
                'description' => 'Start or continue enroll fingerprint for finger 0',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'BtlEnroll1',
                'apdu' => '00 E0 01 00',
                'channel' => 'BTL',
                'requireData' => 0,
                'responseType' => 'bytes',
                'timeout' => 1000,
                'description' => 'Start or continue enroll fingerprint for finger 1',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'BtlPowerOnSE',
                'apdu' => '00 E0 05 00',
                'channel' => 'BTL',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 1500,
                'description' => 'Blueooth power on secure element',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'BtlPowerOffSE',
                'apdu' => '00 E0 06 00',
                'channel' => 'BTL',
                'requireData' => 0,
                'responseType' => NULL,
                'timeout' => 1000,
                'description' => 'Blueooth power off secure element',
                'crc' => NULL,
                'created_at' => '2023-12-11 14:52:25',
                'updated_at' => '2023-12-11 14:52:25',
            ),
        ));
        
        
    }
}